export { default as Hero } from './hero/Hero'
export { default as Navbar } from './navbar/Navbar'
export { default as Work } from './work/Work'
export { default as Services } from './services/Services'
export { default as About } from './about/About'
